### PR TITLE
IL2CPP Build Support

### LINKED ISSUE #100: UsdzExport doesn't work in Build when using IL2CPP, causes Exception (FTV-248)
When scripting backend is set to Mono, I can export USDZ fine from a Windows Desktop build (haven't verified completeness yet, but I do get an USDZ file with geometry in it).

When the scripting backend is set to IL2CPP instead, calling ExportUsdz results in exceptions:
```
Registering plugins: D:/git/schreibkugel/development/Builds/usdzTest/WritingBall_Data/Plugins/share/
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogFormat(String, Object[])
Unity.Formats.USD.InitUsd:Initialize()
Unity.Formats.USD.UsdzExporter:ExportUsdz(String, GameObject)
RuntimeExport:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 48)

NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition. The method we're attempting to marshal is: pxr.UsdCsPINVOKE+SWIGExceptionHelper::SetPendingApplicationException
  at pxr.UsdCsPINVOKE+SWIGExceptionHelper..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at pxr.UsdCsPINVOKE..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at pxr.PlugRegistry.GetInstance () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.InitUsd.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.UsdzExporter.ExportUsdz (System.String usdzFilePath, UnityEngine.GameObject root) [0x00000] in <00000000000000000000000000000000>:0 
  at RuntimeExport.Update () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'pxr.UsdCsPINVOKE.SWIGExceptionHelper' threw an exception.
  at pxr.UsdCsPINVOKE..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at pxr.PlugRegistry.GetInstance () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.InitUsd.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.UsdzExporter.ExportUsdz (System.String usdzFilePath, UnityEngine.GameObject root) [0x00000] in <00000000000000000000000000000000>:0 
  at RuntimeExport.Update () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'pxr.UsdCsPINVOKE' threw an exception.
  at pxr.PlugRegistry.GetInstance () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.InitUsd.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.UsdzExporter.ExportUsdz (System.String usdzFilePath, UnityEngine.GameObject root) [0x00000] in <00000000000000000000000000000000>:0 
  at RuntimeExport.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Unity.Formats.USD.InitUsd:Initialize()
Unity.Formats.USD.UsdzExporter:ExportUsdz(String, GameObject)
RuntimeExport:Update()
 
(Filename: currently not available on il2cpp Line: -1)

ApplicationException: Failed to create: C:\Users\felix\AppData\Local\Temp\zc0u9qvy.z7q\test.usdc
  at USD.NET.Scene.Create (System.String filePath) [0x00000] in <00000000000000000000000000000000>:0 
  at Unity.Formats.USD.UsdzExporter.ExportUsdz (System.String usdzFilePath, UnityEngine.GameObject root) [0x00000] in <00000000000000000000000000000000>:0 
  at RuntimeExport.Update () [0x00000] in <00000000000000000000000000000000>:0 
```

### PR DESCRIPTION
**Pull request by jcowles**
This change is still a work in progress, but it's mostly complete -- I'm posting a draft PR to get feedback. Would probably be best to do a Zoom call to walk through this change together.

The best way to review this is to look at the individual commits.

 * Created a second implementation of type conversion code that doesn't require JIT compilation
 * Created a switch to optionally enable non-JIT type binding
 * Added [MonoPInvokeCallback] to SWIG generated callback code
 * Added [Preserve] tags to all types that must be loaded at run-time
 * Reimplemented DiagnosticDelegate to use a single static function (required by IL2CPP)
 * Removed support for Worker, BackgroundExecutor and async IO, which I believe no one used anyway

[UPDATE] I could not figure out how to force Swig to generate attributes, but I've added a unit test to verify that they are present

Fixes #100

### CODE REVIEW

**Comment by clusty** [comment]
zoom would be nice :)
Can't say I understand the code.

**Comment by judubu** [comment]
@clusty check this thread for a little bit more info: https://github.com/Unity-Technologies/usd-unity-sdk/issues/100#issuecomment-589827375
Count me in the zoom call if it's happening.

**Comment by jcowles** [comment]
@judubu @clusty ok, I updated this with a unit test, added some comments to the edits in the generated code, and updated BUILDING.md

Let me know if you have any more feedback, or hit approve if you feel good about this PR!

**Comment by jcowles** [comment]
oh, this obviously needs an OSX build also, will fix (hooray automation)

**Review by judubu — APPROVED** [review]
Great job!
And thanks for all the additional comments regarding the type binding process.

**Review by clusty — APPROVED** [review]

**Pull request merged**
