### PR TITLE
Fix UsdCs import settings for OSX and Windows (USDU-206)

### PR DESCRIPTION
**Pull request by judubu**
## Purpose of this PR

**Ticket/Jira #:** https://jira.unity3d.com/browse/USDU-206

New settings are:

- OSX
usdcs_import_settings_OSX

- Windows
usdcs_import_settings_WIN

## Testing

**Functional Testing status:**

@clusty can you do an IOS build for me please? Or do you know how I should trigger an IOs build on yamato?

## Overall Product Risks

**Complexity:**

Low

**Halo Effect:**

Low

## Additional information

**Note to reviewers:**

**Reminder:**

- [ ] Add entry in CHANGELOG.md _(if applicable)_

### CODE REVIEW

**Comment by mirceaispas** [comment]
@IlliaKo Can you please validate this PR against https://jira.unity3d.com/browse/USDU-66 and also the builds on Windows and MacOS

**Comment by clusty** [comment]
I would add a unit test that checks that there are no weird libraries when you do a build:
Here's an example of such a test: https://github.cds.internal.unity3d.com/unity/com.unity.recorder/blob/4bbecfc3cc7a5eb52efa8b35a4de4582559cd72e/projects/recorder-tests/Assets/Tests/Editor/MovieRecorder/BuildSupportTests.cs

**Review by clusty — APPROVED** [review]

**Review by IlliaKo — CHANGES_REQUESTED** [review]
Issue is still reproducible on my side.

**Comment by vickycl** [comment]
FIxed in https://github.com/Unity-Technologies/usd-unity-sdk/pull/333

**Pull request closed without merging**
